### ISSUE TITLE
Question/documentation request: How do you use this with an IDE?

### ISSUE THREAD

**Issue by chrisirhc** [theoremlp/rules_mypy#22]
Hi, I'm trying to integrate this with an IDE such as VS Code's mypy extension (https://github.com/microsoft/vscode-mypy) .
One way to do this might be to use the mypy_cli and point the IDE's mypy extension to the mypy binary. 
To test this approach, I tried running mypy py_binary target from mypy_cli like so:
```shell
bazel run //tools/mypy:mypy_cli $PWD/<location of code>
```

tools/mypy/BUILD.bazel contains:
```
load("@rules_mypy//mypy:mypy.bzl", "mypy_cli")
mypy_cli(name = "mypy_cli")
```

However, I'm seeing many errors where the dependencies aren't found. I'm guessing this is because the aspect has logic to find the dependencies and add it to the MYPY path.
I was wondering how you get around this to set up the mypy linting with the IDE, or if this is currently only used via the commandline.

**Comment by mark-thm** [comment]
We use these rules as follows:
 - we use [rules_uv](https://github.com/theoremlp/rules_uv) to make a virtual env
 - we make sure the IDE uses that virtual env
 - we use the IDE-native integrated type-checking with that virtual env

For VSCode we typically just enable PyRight, which is pretty close in terms of feedback, and will use the command line to enforce mypy.

For IntelliJ we typically do something like configure a file watcher to run Bazel as you indicated above, modulo we ensure the virtual env is activated so that 3rd party deps get picked up.

Both of these are partial solutions since nothing is actually helping the IDE understand the real dependency chain for an individual source set, and the idea of how Bazel groups files together is not the native way that most IDEs treat directories of sources.
